# Site settings
title: "Data Exploration"
email: jpgallagher@gmail.com
description: "A bit of data always piques my curiosity.  After a few questions and some hard work, I love the learning."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://secure.gravatar.com/avatar/01b9b2ca300bdd68f4742191682fd05b?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: JohnPGallagher7
github_username:  jpgallagher1
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/john-gallagher-7348b163/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://jpgallagher1.github.io\">John Gallagher</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
